from cmath import sqrt

print(".......................")
print("Hola bienvenido -.- ")
print(".......................")
a = int(input("Inserta A: "))
b = int(input("Inserta B: "))
c = int(input("Inserta C: "))
u = int(b*b)
d = (4*a*c)
t = (u-d)
r = (sqrt(t))
i = (-b)
s = (2*a)
e = (i+r)
o = (i-r)
n = (e/s)
z = (o/s)
print(".......................")
print("La primera respuesta es: " + str(n))
print(".......................")
print("La segunda respuesta es: " + str(z))
